// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\store\sql.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSQLPinger is a mock of SQLPinger interface.
type MockSQLPinger struct {
	ctrl     *gomock.Controller
	recorder *MockSQLPingerMockRecorder
}

// MockSQLPingerMockRecorder is the mock recorder for MockSQLPinger.
type MockSQLPingerMockRecorder struct {
	mock *MockSQLPinger
}

// NewMockSQLPinger creates a new mock instance.
func NewMockSQLPinger(ctrl *gomock.Controller) *MockSQLPinger {
	mock := &MockSQLPinger{ctrl: ctrl}
	mock.recorder = &MockSQLPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLPinger) EXPECT() *MockSQLPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockSQLPinger) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLPingerMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLPinger)(nil).Ping))
}
